FROM continuumio/miniconda3

RUN apt-get update 
RUN apt-get install -y python3-pip
RUN apt install -y python3-flask

COPY . /social
WORKDIR /social

EXPOSE 5000

SHELL ["/bin/bash", "--login", "-c"]subuser
RUN echo "export FLASK_APP=app.py" >> ~/.bashrc
CMD [“/bin/bash”]